### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by zhanghai** [DreaminginCodeZH/PatternLock#1]
Publish on my own, or use [jitpack.io](https://jitpack.io/#DreaminginCodeZH/PatternLock/)

See https://github.com/jitpack/jitpack.io/blob/master/ANDROID.md

Will do this if I had the time.

**Comment by jitpack-io** [comment]
Hi! 
It works already: https://jitpack.io/#DreaminginCodeZH/PatternLock/bc7180210b
Just needs a GitHub release so that there's a version:)

**Comment by zhanghai** [comment]
@jitpack-io 
Just added a release (and a pom.xml in addition). Wonder if that is enough? Didn't find somewhere to check the build log.

**Comment by jitpack-io** [comment]
Yepp, works great: https://jitpack.io/#DreaminginCodeZH/PatternLock/v1.0.0

**Comment by zhanghai** [comment]
@jitpack-io But I've got two modules, sample and library, how can I get them from that dependency?

**Comment by jitpack-io** [comment]
@DreaminginCodeZH It will only publish the library since that's what other people will use as a dependency. It should be possible to publish the sample binary but seems like it's more useful to have it in source form.

**Comment by zhanghai** [comment]
Thanks for your help, closing this issue.
