### ISSUE TITLE
Getting the finger size at every point of the pattern

### ISSUE THREAD

**Issue by evxzibit** [DreaminginCodeZH/PatternLock#12]
Hi,

Great job on this project.  This is not and issue by the way. I am trying to get the finger size of the user when the pattern is being drawn using getSize(), but i guess i need to get the average finger size at each point of ht drawn pattern to get more accuracy. e.g if pattern is 1-2-3-4 then i get the finger size at point 1,2,3 and 4. The purpose is for me to identify the user on the drawn pattern AND on his average finger size to make it more unique.

What i did: 
i set up a global finger size variable and i assign it a value on the function here PatternView.java#L829  using event.getSize(). If i am correct, this just gets the finger size only at one point during the whole pattern draw.

Could you please guide me into getting the finger size at every point of the pattern?

Thank you

**Comment by zhanghai** [comment]
Maybe you can have a `List` field empty at start, appended when `hitCell != null`  and avaraged and cleared when finished?

(I don't think taking user's finger size from touch event as a parameter of authentication is good idea, though.)

**Comment by evxzibit** [comment]
Ah good idea i will try this thank you. Could you please tel me why you think it is not a good idea? I was thinking of getting the finger size and pressure at everypoint to produce somekind of 'biometric' recognition on pattern lock. So instead of only the pattern being compared? Then it will be the pattern, finger size and pressure all together. Please share your thought i don't mind.

Thank you.

**Comment by zhanghai** [comment]
Well just some personnal experience - I'm using a pattern lockscreen and I've been drawing patterns a lot. Sometimes I draw it much too quickly that it is even not recognized. And it sounds not so usable when much more requirements are to be met. (What if the touch event sent by system happens at the time when I'm swiping so fast that the size is much smaller than usual? Just some wild guesses and feelings on reliability like this.)

**Comment by evxzibit** [comment]
I see your point and I totally agree. I Am actually wanting to prove(for my master thesis) that adding the finger details might enhance pattern recognition, and if i can make it work like 80% of the time that will be great.thanks again for your input.
