### ISSUE TITLE
Disable cancel button

### ISSUE THREAD

**Issue by tfreeman82** [DreaminginCodeZH/PatternLock#16]
Is there a way to disable the cancel button to force the use to input their pattern?

**Comment by zhanghai** [comment]
Override onCreate, and add mLeftBotton.setVisibility(View.GONE).

**Comment by tfreeman82** [comment]
Which class would that be in? I added the library with Gradle and see on here that the BasePatternActivity is where the buttons are declared but don't know how to access it.

**Comment by zhanghai** [comment]
You extend SetPatternActivity or ConfirmPatternActivity; it's declared protected.
