### ISSUE TITLE
请问可以自己重新定义绘制小圆点的样式和滑动的动画么

### ISSUE THREAD

**Issue by jasoncheng911** [DreaminginCodeZH/PatternLock#18]

**Comment by zhanghai** [comment]
可以修改颜色，但更多的修改不会很简单，因为所有的绘制都[ hardcode 在 PatternView.java 中](https://github.com/DreaminginCodeZH/PatternLock/blob/master/library/src/main/java/me/zhanghai/android/patternlock/PatternView.java#L1114)，需要你自己改代码。或者往回几个版本，库里 Android 4.x 对应的 PatternView 时候是能够自定义图像资源的。

**Comment by jasoncheng911** [comment]
@DreaminginCodeZH  3Q  我看下
