### ISSUE TITLE
Programtically set pattern lock and retrieve pattern code

### ISSUE THREAD

**Issue by haris-bhatti** [DreaminginCodeZH/PatternLock#23]
how can i set the pattern lock by sending a code eg. 12369 and this code will be set as my pattern lock, and how can retrieve this pattern code? please help me, i'm using this patternLock in my project and i want to implement this functionality. Thanks

**Comment by zhanghai** [comment]
See [this](https://github.com/DreaminginCodeZH/PatternLock/blob/master/sample/src/main/java/me/zhanghai/android/patternlock/sample/app/AboutActivity.java#L24) for setting the pattern and [this](https://github.com/DreaminginCodeZH/PatternLock/blob/master/sample/src/main/java/me/zhanghai/android/patternlock/sample/app/SetPatternActivity.java) for getting the pattern.

**Comment by haris-bhatti** [comment]
Hey Zhang,
thank you for this. I really appreciate your efforts and work.

Regards,
Haris Bhatti
Android Developer
SDSol Technologies ​
