### ISSUE TITLE
In Fragmetns pattern not working

### ISSUE THREAD

**Issue by k-srikanth** [DreaminginCodeZH/PatternLock#24]
Hi,

I am unable to set pattern on Fragments.If i draw pattern in fragment horizontally nothing is drawn.
Please help me to resolve this issue.

Regards,
Srikanth.k

**Comment by zhanghai** [comment]
You need to post your Java code and XML layout, or nobody can tell what's happening.

And in the meantime, you can compare your code to [the sample of this library](https://github.com/DreaminginCodeZH/PatternLock/blob/master/sample/src/main/java/me/zhanghai/android/patternlock/sample/app/SetPatternActivity.java).
