### ISSUE TITLE
how to set up a  simple lock for app?

### ISSUE THREAD

**Issue by pourya0111** [DreaminginCodeZH/PatternLock#25]
hey there and many thanks for this awesome library
as 'im new to android studio and your sample is to complicated for my current level can you provide some simple codes where there's a switch on main activity when switching on it will ask for pattern and after setting it it will lock the app 
also when switching off will shut down the lock
sorry for bad english
any help will greatly appreciated
thanks in advance
regards

**Comment by zhanghai** [comment]
Hi, the sample activity has a switch (`SwitchPreference`) in it, and when enabled it requries pattern unlock. The sample has already been the most basic one and leaving out anything will make the flow incomplete. You can always choose to read the part of source code that you find interesting.
