### ISSUE TITLE
onCancel in SetPatternActivity

### ISSUE THREAD

**Issue by macroday** [DreaminginCodeZH/PatternLock#5]
Hi, Add onCancel and onConfirm method in setPatternActivity class. It will be good to us to use it different ways.

**Comment by zhanghai** [comment]
You can check for RESULT_CANCEL in the calling activity. Does this satisfy your need?

**Comment by macroday** [comment]
Sorry, i donna how to check the RESULT_CANCEL or not in the code. Could you
give proper example?

On Tue, Apr 19, 2016 at 4:19 PM, Zhang Hai notifications@github.com wrote:

> You can check for RESULT_CANCEL in the calling activity. Does this satisfy
> your need?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/DreaminginCodeZH/PatternLock/issues/5#issuecomment-211856047

## 

Regards,
Ganesh K
Wings Interactive India,
9944345752

**Comment by zhanghai** [comment]
Override Activity.onActivithResult() in the activity that starts SetPatternActivity. See the documentation for that method to get more detail.

I suggest your using this method because user can quit that SetPatternActivity with approaches other than pressing cancel - such as pressing back. (You can override Activity.finish(), though.)

**Comment by macroday** [comment]
Thank you Zhang.

On Tue, Apr 19, 2016 at 5:30 PM, Zhang Hai notifications@github.com wrote:

> Override Activity.onActivithResult() in the activity that starts
> SetPatternActivity. See the documentation for that method to get more
> detail.
> 
> I suggest your using this method because user can quit that
> SetPatternActivity with approaches other than pressing cancel - such as
> pressing back. (You can override Activity.finish(), though.)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/DreaminginCodeZH/PatternLock/issues/5#issuecomment-211882790

## 

Regards,
Ganesh K
Wings Interactive India,
9944345752
