### ISSUE TITLE
recurring attempts

### ISSUE THREAD

**Issue by andrewalken** [DreaminginCodeZH/PatternLock#6]
is there a way to change it so it doesn't dismiss on an incorrect pattern. i want to be able to keep trying until it's correct

**Comment by zhanghai** [comment]
It does not finish on wrong pattern - see [ConfirmPatternActivity.java#L106](https://github.com/DreaminginCodeZH/PatternLock/blob/master/library/src/main/java/me/zhanghai/android/patternlock/ConfirmPatternActivity.java#L106).

**Comment by andrewalken** [comment]
My mistake, Sorry
